function [fitresult, gof] = createFit1(grepsearch_cpu, grepsearch_tct)
%CREATEFIT1(GREPSEARCH_CPU,GREPSEARCH_TCT)
%  Create a fit.
%
%  Data for 'grepsearch model fit' fit:
%      X Input : grepsearch_cpu
%      Y Output: grepsearch_tct
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Oct-2013 18:36:05


%% Fit: 'grepsearch model fit'.
[xData, yData] = prepareCurveData( grepsearch_cpu, grepsearch_tct );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.895775889852398 0.00360043611152319 0.0229432157634263 0.0318090334165192];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'grepsearch model fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'grepsearch_tct vs. grepsearch_cpu', 'grepsearch model fit', 'Location', 'NorthEast' );
% Label axes
xlabel( 'grepsearch_cpu' );
ylabel( 'grepsearch_tct' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'grepsearch model fit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( 'grepsearch_cpu' );
ylabel( 'grepsearch_tct' );
grid on


